### ISSUE TITLE
11章11.22のテストが通らない

### ISSUE THREAD

**Issue by 1noseA** [1noseA/rails_tutorial#2]
エラー文は
ERROR["test_account_activation", UserMailerTest, 1.1475455650070217]
 test_account_activation#UserMailerTest (1.15s)
ActionView::Template::Error:         ActionView::Template::Error: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
            app/views/user_mailer/account_activation.html.erb:9:in `_app_views_user_mailer_account_activation_html_erb__2839570932751603762_47080722274280'
            app/mailers/user_mailer.rb:5:in `account_activation'
            test/mailers/user_mailer_test.rb:9:in `block in <class:UserMailerTest>'

見返しても調べても分からない。
先を進めてもエラーが増えてしまうだけ。全てテンプレートエラー。
11章終了時のテストエラー

ERROR["test_login_with_remembering", UsersLoginTest, 0.47860913901240565]
 test_login_with_remembering#UsersLoginTest (0.48s)
NoMethodError:         NoMethodError: undefined method `remember_token' for nil:NilClass
            test/integration/users_login_test.rb:42:in `block in <class:UsersLoginTest>'

ERROR["test_valid_signup_information_with_account_activation", UsersSignupTest, 0.8660609340004157]
 test_valid_signup_information_with_account_activation#UsersSignupTest (0.87s)
ActionView::Template::Error:         ActionView::Template::Error: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
            app/views/user_mailer/account_activation.html.erb:9:in `_app_views_user_mailer_account_activation_html_erb__2839570932751603762_47080723438780'
            app/mailers/user_mailer.rb:5:in `account_activation'
            app/models/user.rb:51:in `send_activation_email'
            app/controllers/users_controller.rb:21:in `create'
            test/integration/users_signup_test.rb:25:in `block (2 levels) in <class:UsersSignupTest>'
            test/integration/users_signup_test.rb:24:in `block in <class:UsersSignupTest>'

ERROR["test_account_activation", UserMailerTest, 1.0184472050168552]
 test_account_activation#UserMailerTest (1.02s)
ActionView::Template::Error:         ActionView::Template::Error: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
            app/views/user_mailer/account_activation.html.erb:9:in `_app_views_user_mailer_account_activation_html_erb__2839570932751603762_47080723438780'
            app/mailers/user_mailer.rb:5:in `account_activation'
            test/mailers/user_mailer_test.rb:9:in `block in <class:UserMailerTest>'

**Comment by 1noseA** [comment]
12.13のテストをしたとき、エラーが１に減っていた。
ERROR["test_login_with_remembering", UsersLoginTest, 1.1695671640045475]
 test_login_with_remembering#UsersLoginTest (1.17s)
NoMethodError:         NoMethodError: undefined method `remember_token' for nil:NilClass
            test/integration/users_login_test.rb:42:in `block in <class:UsersLoginTest>'
自分で新規登録して有効化したから？

**Comment by 1noseA** [comment]
https://teratail.com/questions/141615
（test/integration/users_login_test.rbの
assigns(:user).remember_token
という部分が問題で、assigns(:user)でSessionControllerの@user変数を取れるのですが
SessionController#createで@userへの代入を行っていなかった為nilになってしまうのが問題です。）
にあるように
session_controllerのcreateにuser→@userにしたらテスト通った。
